name: ${project.parent.name}
version: ${project.parent.version}
author: NEZNAMY
main: me.neznamy.tab.platforms.bukkit.Main
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, UltraPermissions, LuckPerms, Essentials, LibsDisguises]
website: "https://www.spigotmc.org/resources/57806/"
description: ${project.parent.description}
commands:
  tab: