# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  header:
    - "&3&lServer name"
    - "&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<"
    - "&7Online players: &f%online%"
    - "&6Online staff: &e%staffonline%"
    - ""
    - "%animation:MyAnimation1%"
  footer:
    - "%animation:MyAnimation1%"
    - "%animation:time%"
    - "%animation:ping-tps%"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Visit our webpage %animation:web%"
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2-world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  default-bars:
    - ServerInfo
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"
    test:
      display-condition: "permission:tab.bossbar.test"
      style: PROGRESS
      color: WHITE
      progress: "100"
      text: "test"

global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2

# https://github.com/NEZNAMY/TAB/wiki/config.yml#placeholders
placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements-(premium-only)
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders-(premium-only)
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"
  health:
    conditions:
      - "%health%<21"
      - "%health%>15"
    type: AND
    yes: "Healthy!"
    no: "Damaged!"

# https://github.com/NEZNAMY/TAB/wiki/Optimizing-the-plugin#3---placeholder-refresh-intervals
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

#if none of the above fits your needs, you can enable this to give groups using tab.group.<group name from the list below> permission
assign-groups-by-permissions: false

#if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

use-bukkit-permissions-manager: false